FROM  python:3.6

COPY requirements.txt /root/processing/requirements.txt

WORKDIR /root/processing

RUN pip install -r requirements.txt

COPY . /root/processing/

CMD uwsgi --http :80 --module ui:server
